Repository wraft/wraft, pull requests merged in 2025-03, with the labels that each got.

#46 feat: add image to generate document
  Dockerfile
  Dockerfile.dev
  README.md
  config/config.exs
  lib/wraft_doc/assets/asset.ex
  lib/wraft_doc/assets/assets.ex
  lib/wraft_doc/doc_conversion.ex
  lib/wraft_doc/documents/documents.ex
  lib/wraft_doc_web/controllers/asset_controller.ex
  lib/wraft_doc_web/email/email.ex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/uploaders/asset_uploader.ex
  lib/wraft_doc_web/views/asset_view.ex
  mix.exs
  mix.lock
  priv/pandoc_filters/filters.yaml
  priv/pandoc_filters/s3_image.lua
  priv/repo/migrations/20250219125828_create_document_asset_table.exs
  test/wraft_doc_web/email/email_test.exs
Labels: enhancement

#47 fix: add backend url as env variable for image generation
  .env.example
  config/config.exs
  lib/wraft_doc/documents/documents.ex
Labels: bug

#51 fix: resolve image filter path issue and docker lua compatibility
  Dockerfile
  lib/wraft_doc/documents/documents.ex
  priv/pandoc_filters/s3_image.lua
Labels: bug

#53 fix: add version preload for build in pipeline pathway
  lib/wraft_doc/documents/documents.ex
  mix.exs
Labels: bug

#54 feat: docx to prosemirror conversion
  lib/wraft_doc/doc_conversion.ex
  lib/wraft_doc/utils/markdown_to_prosemirror.ex
  lib/wraft_doc_web/controllers/document_controller.ex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/views/document_view.ex
  mix.exs
  mix.lock
  priv/repo/data/rbac/permissions.csv
Labels: enhancement

#55 fix: correctly resolve pandoc_path in docker
  lib/wraft_doc/doc_conversion.ex
  lib/wraft_doc/utils/markdown_to_prosemirror.ex
Labels: bug

#57 feat: typesense reindex
  lib/wraft_doc_web/controllers/search_controller.ex
  lib/wraft_doc_web/router.ex
Labels: enhancement

#58 feat: add updation for email and password via admin panel
  lib/wraft_doc/internal_users/internal_user.ex
  lib/wraft_doc_web/admin/internal_user_admin.ex
Labels: enhancement

#61 fix: documents not indexing
  lib/wraft_doc/search/encoder.ex
Labels: bug

#48 fix: transfer ownership, improvements in notification module and switch organisation fixes
  lib/wraft_doc/documents/documents.ex
  lib/wraft_doc/notifications/notification_messages.ex
  lib/wraft_doc/notifications/notifications.ex
  lib/wraft_doc/organisation/enterprise.ex
  lib/wraft_doc/organisation/organisation.ex
  lib/wraft_doc_web/controllers/instance_controller.ex
  lib/wraft_doc_web/controllers/organisation_controller.ex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/views/organisation_view.ex
  priv/repo/migrations/20250214083221_add_owner_to_organisation.exs
Labels: bug

#60 feat: add import frame zip
  lib/wraft_doc/assets/asset.ex
  lib/wraft_doc/assets/assets.ex
  lib/wraft_doc/content_types/content_types.ex
  lib/wraft_doc/documents/documents.ex
  lib/wraft_doc/frames/frame.ex
  lib/wraft_doc/frames/frame_asset.ex
  lib/wraft_doc/frames/frames.ex
  lib/wraft_doc/frames/wraft_json.ex
  lib/wraft_doc/layouts/layouts.ex
  lib/wraft_doc/template_assets/template_assets.ex
  lib/wraft_doc/template_assets/wraft_json.ex
  lib/wraft_doc/utils/file_helper.ex
  lib/wraft_doc/utils/file_validator.ex
  lib/wraft_doc_web/controllers/content_type_controller.ex
  lib/wraft_doc_web/controllers/frame_controller.ex
  lib/wraft_doc_web/controllers/layout_controller.ex
  lib/wraft_doc_web/uploaders/asset_uploader.ex
  lib/wraft_doc_web/uploaders/frame_thumbnail_uploader.ex
  lib/wraft_doc_web/views/frame_view.ex
  priv/repo/migrations/20250302064855_add_frame_asset.exs
  test/support/factory.ex
  test/wraft_doc/document/document_test.exs
  test/wraft_doc/frames/wraft_json_test.exs
Labels: enhancement

#63 feat: add oban web intergration
  lib/wraft_doc_web/endpoint.ex
  lib/wraft_doc_web/router.ex
  mix.exs
  mix.lock
Labels: enhancement

#68 fix: remove redundant subcription
  lib/wraft_doc/user/account.ex
Labels: bug, Priority: Critical

#66 feat: clm expiry and remainder
  config/config.exs
  lib/wraft_doc/application.ex
  lib/wraft_doc/documents/documents.ex
  lib/wraft_doc/documents/instance/contract_meta.ex
  lib/wraft_doc/documents/reminder.ex
  lib/wraft_doc/documents/reminders.ex
  lib/wraft_doc/notifications/notification_messages.ex
  lib/wraft_doc/schedulers/refresh_dashboard_stats.ex
  lib/wraft_doc/user/user.ex
  lib/wraft_doc/workers/email_worker.ex
  lib/wraft_doc/workers/reminder_worker.ex
  lib/wraft_doc_web/controllers/instance_controller.ex
  lib/wraft_doc_web/controllers/organisation_controller.ex
  lib/wraft_doc_web/controllers/reminder_controller.ex
  lib/wraft_doc_web/email/email.ex
  lib/wraft_doc_web/mjml/document_reminder.ex
  lib/wraft_doc_web/mjml/templates/document_reminder.mjml.eex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/views/instance_view.ex
  lib/wraft_doc_web/views/reminder_view.ex
  priv/repo/migrations/20250318124219_create_document_reminder.exs
Labels: enhancement
