Repository wraft/wraft, pull requests merged in 2025-02, with the labels that each got.

#28 chore: add paddle url to config
  .env.example
  config/config.exs
  config/dev.exs
  config/prod.exs
  lib/wraft_doc/billing/paddle_api.ex
Labels: bug

#14 feat: typesense
  .env.example
  .gitignore
  config/runtime.exs
  docker-compose.yml
  lib/wraft_doc/application.ex
  lib/wraft_doc/document/content_type.ex
  lib/wraft_doc/document/data_template.ex
  lib/wraft_doc/document/layout.ex
  lib/wraft_doc/document/theme.ex
  lib/wraft_doc/organisation/flow.ex
  lib/wraft_doc/search/encoder.ex
  lib/wraft_doc/search/presets.ex
  lib/wraft_doc/search/typesense.ex
  lib/wraft_doc/search/typesense_server.ex
  lib/wraft_doc_web/controllers/content_type_controller.ex
  lib/wraft_doc_web/controllers/data_template_controller.ex
  lib/wraft_doc_web/controllers/flow_controller.ex
  lib/wraft_doc_web/controllers/layout_controller.ex
  lib/wraft_doc_web/controllers/search_controller.ex
  lib/wraft_doc_web/controllers/theme_controller.ex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/views/search_view.ex
  mix.exs
  mix.lock
Labels: enhancement

#24 feat: add users to collaborate and engage with the document
  config/dev.exs
  config/prod.exs
  lib/wraft_doc/auth_tokens.ex
  lib/wraft_doc/auth_tokens/auth_token.ex
  lib/wraft_doc/document/comment.ex
  lib/wraft_doc/document/content_collab.ex
  lib/wraft_doc/document/content_collaboration.ex
  lib/wraft_doc/document/content_type.ex
  lib/wraft_doc/document/counter_parties.ex
  lib/wraft_doc/document/document.ex
  lib/wraft_doc/document/instance.ex
  lib/wraft_doc/document/instance/contract_meta.ex
  lib/wraft_doc/document/instance/document_meta.ex
  lib/wraft_doc/document/instance_version.ex
  lib/wraft_doc/ecto_type/document_meta_type.ex
  lib/wraft_doc/organisation/enterprise.ex
  lib/wraft_doc/organisation/state.ex
  lib/wraft_doc/organisation/state_user.ex
  lib/wraft_doc/user/account.ex
  lib/wraft_doc/user/user.ex
  lib/wraft_doc/workers/email_worker.ex
  lib/wraft_doc/y_documents/y_documents.ex
  lib/wraft_doc/y_ecto.ex
  lib/wraft_doc/y_ecto_adapter.ex
  lib/wraft_doc_web/auth/current_organisation.ex
  lib/wraft_doc_web/channels/document_channel.ex
  lib/wraft_doc_web/channels/user_socket.ex
  lib/wraft_doc_web/controllers/comment_controller.ex
  lib/wraft_doc_web/controllers/content_type_controller.ex
  lib/wraft_doc_web/controllers/instance_controller.ex
  lib/wraft_doc_web/controllers/instance_guest_controller.ex
  lib/wraft_doc_web/controllers/state_controller.ex
  lib/wraft_doc_web/email/email.ex
  lib/wraft_doc_web/mjml/document_instance_share.ex
  lib/wraft_doc_web/mjml/templates/document_instance_share.mjml.eex
  lib/wraft_doc_web/plug/action_logging.ex
  lib/wraft_doc_web/plug/authorized.ex
  lib/wraft_doc_web/router.ex
  lib/wraft_doc_web/views/content_type_view.ex
  lib/wraft_doc_web/views/flow_view.ex
  lib/wraft_doc_web/views/instance_guest_view.ex
  lib/wraft_doc_web/views/instance_version_view.ex
  lib/wraft_doc_web/views/instance_view.ex
  lib/wraft_doc_web/views/state_view.ex
  lib/wraft_doc_web/views/user_view.ex
  mix.exs
  mix.lock
  priv/repo/data/rbac/permissions.csv
  priv/repo/migrations/20241112101834_add_document_type_and_meta.exs
  priv/repo/migrations/20241204042843_content_collaboration.exs
  priv/repo/migrations/20241204044337_counter_parties.exs
  priv/repo/migrations/20241213141328_add_invited_and_revoked_at_fields_in_collab_table.exs
  priv/repo/migrations/20241218062507_create_y_documents.exs
  priv/repo/migrations/20241219063734_add_content_id_field_to_state_users_table.exs
  priv/repo/migrations/20250206094949_add_type_and_hybrid_versioning_to_instance_version.exs
  test/support/factory.ex
  test/wraft_doc/document/instance_version_test.exs
Labels: enhancement

#34 fix: update unique index and add double entries for initial versioning
  lib/wraft_doc/document/document.ex
  lib/wraft_doc/document/instance_version.ex
  priv/repo/migrations/20250211092817_update_version_unique_index.exs
Labels: bug, Priority: Critical

#35 fix: add organisation membership status in token verification api
  lib/wraft_doc_web/controllers/organisation_controller.ex
  lib/wraft_doc_web/views/organisation_view.ex
Labels: bug

#40 fix: organisation filter bugs and data_template renamed
  lib/wraft_doc/document/data_template.ex
  lib/wraft_doc/search/encoder.ex
  lib/wraft_doc/search/typesense.ex
  lib/wraft_doc_web/controllers/search_controller.ex
Labels: bug
